name: Build binary files for release

on:
  release:
    types:
      - 'created'
      - 'edited'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'windows-latest'
          - 'ubuntu-latest'
          - 'macos-latest'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: pyinstaller lmao.spec
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install setuptools wheel build
    - run: python -m build
    - uses: pypa/gh-action-pypi-publish@release/v1
