name: Build and run tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Create venv
      run: python -m venv venv
    - name: Activate venv
      run: source venv/bin/activate
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Set env variables
      run: echo "PYTHONPATH=$(echo ./src:./src/lmao:$PYTHONPATH)" >> $GITHUB_ENV
    - name: Check project version
      run: python -m main --version
